[package]
name = "multiproof"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-keccak = { version = "2.0.0", features = ["keccak"] }
log = "0.4.22"

[dev-dependencies]
test-log = "*"
